#!/usr/bin/python
# Copyright (c) Members of the EGEE Collaboration. 2004. 
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.  
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#     http://www.apache.org/licenses/LICENSE-2.0 
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License.

import sys
import re
import socket
import time

def main():

    pRegex = re.compile('^\s*([^=\s]+)\s*=([^$]+)$')

    config = {}

    infoprovVersion = "1.1"
    hostname = socket.getfqdn()
    now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    
    conffile = None
    foundErr = False
    try:
        if len(sys.argv) <> 2:
            raise Exception("Usage: glite-ce-glue2-tostorageservice-static <config-file>")
            
        conffile = open(sys.argv[1])
        for line in conffile:
            parsed = pRegex.match(line)
            if parsed:
                config[parsed.group(1)] = parsed.group(2).strip(' \n\t"')
            else:
                tmps = line.strip()
                if len(tmps) > 0 and not tmps.startswith('#'):
                    raise Exception("Error parsing configuration file " + sys.argv[1])
    
        for mItem in ['ComputingServiceId',
                      'CloseSEs']:
            if not mItem in config:
                raise Exception("Missing attribute %s" % mItem)
        if not "EMIES" in config:
            config["EMIES"] = "no"
        if not "ESComputingServiceId" in config and config["EMIES"] == "yes":
            config["ESComputingServiceId"] = hostname + "_ESComputingElement"
    
    except Exception, ex:
        sys.stderr.write(str(ex) + '\n')
        foundErr = True

    if conffile:
        conffile.close()
    if foundErr:
        sys.exit(1)

    out = sys.stdout

    tmpl = config['CloseSEs'].strip("()").split(',')
    seTable = []
    for line in tmpl:
        tmpt = line.strip('() \n\t').split()
        if len(tmpt) == 3:
            seTable.append(tmpt)
    
    srvList = [config['ComputingServiceId']]
    if config['EMIES'] == 'yes':
        srvList.append(config['ESComputingServiceId'])

    for srvId in srvList:
        
        for seDefs in seTable:
            
            out.write("dn: GLUE2ToStorageServiceID=%s_%s,GLUE2ServiceID=%s,GLUE2GroupID=resource,o=glue\n"
                       % (srvId, seDefs[0], srvId))
            out.write("objectClass: GLUE2Entity\n")
            out.write("objectClass: GLUE2ToStorageService\n")
            out.write("GLUE2ToStorageServiceID: %s_%s\n" % (srvId, seDefs[0]))
            out.write("GLUE2EntityCreationTime: %s\n" % now)
            out.write("GLUE2EntityOtherInfo: InfoProviderName=glite-ce-glue2-tostorageservice-static\n")
            out.write("GLUE2EntityOtherInfo: InfoProviderVersion=%s\n" % infoprovVersion)
            out.write("GLUE2EntityOtherInfo: InfoProviderHost=%s\n" % hostname)
            out.write("Glue2EntityName: %s_%s\n" % (srvId, seDefs[0]))
            out.write("GLUE2ToStorageServiceLocalPath: %s\n" % seDefs[1])
            out.write("GLUE2ToStorageServiceRemotePath: %s\n" % seDefs[2])
            out.write("GLUE2ToStorageServiceComputingServiceForeignKey: %s\n" % srvId)
            out.write("GLUE2ToStorageServiceStorageServiceForeignKey: %s\n" % seDefs[0])
            out.write("\n")




if __name__ == "__main__":
    main()

